export const categories = {
  HistoricalFigures: [
    { prompt: "Albert Einstein DJing at a pool party on the Las Vegas Strip, surrounded by art deco signs.", image: "/assets/images/einstein_pool.jpg" },
    { prompt: "Napoleon Bonaparte riding a horse in a Walmart aisle filled with holiday decorations.", image: "/assets/images/napoleon_walmart.jpg" },
    { prompt: "Cleopatra hosting a late-night talk show with a modern neon backdrop.", image: "/assets/images/cleopatra_talkshow.jpg" },
    { prompt: "Leonardo da Vinci building a futuristic robot in his Renaissance workshop.", image: "/assets/images/da_vinci_robot.jpg" },
  ],
  LensStyle: [
    { prompt: "Create a cyberpunk version of [Person X] in a bustling neon city.", image: "/assets/images/cyberpunk.jpg" },
    { prompt: "Imagine [Person X] as a 90s grunge album cover artist.", image: "/assets/images/grunge_album.jpg" },
    { prompt: "Transform [Person X] into a whimsical fairy-tale character in a misty enchanted forest.", image: "/assets/images/fairy_tale.jpg" },
    { prompt: "Reimagine [Person X] as a heroic figure in a sci-fi intergalactic war.", image: "/assets/images/sci_fi_hero.jpg" },
  ],
  CameraAngles: [
    { prompt: "An establishing shot of a cozy village nestled in the mountains during sunrise.", image: "/assets/images/village_establishing.jpg" },
    { prompt: "A close-up of a blooming flower with dew drops glistening on its petals.", image: "/assets/images/flower_close_up.jpg" },
    { prompt: "An aerial shot of a bustling city with cars and people moving through busy streets.", image: "/assets/images/city_aerial.jpg" },
    { prompt: "An extreme close-up of an eye with the reflection of a glowing computer screen.", image: "/assets/images/eye_extreme_close_up.jpg" },
    { prompt: "A tracking shot of a cyclist racing through a forest trail, with sunlight filtering through the trees.", image: "/assets/images/cyclist_tracking.jpg" },
    { prompt: "A wide shot of a vast desert with sand dunes and a lone traveler walking towards the horizon.", image: "/assets/images/desert_wide.jpg" },
    { prompt: "A two-shot of two friends laughing together at a park bench, surrounded by colorful flowers.", image: "/assets/images/two_shot_friends.jpg" },
  ],
  TheColorBlue: [
    { prompt: "A majestic waterfall cascading into a cerulean pool, with golden fish leaping from the water under a clear sky.", image: "/assets/images/cerulean_waterfall.jpg" },
    { prompt: "A sapphire dragon sleeping in an ice cave illuminated by glowing icicles.", image: "/assets/images/sapphire_dragon.jpg" },
    { prompt: "A deep-sea diver exploring an ancient teal temple surrounded by glowing jellyfish.", image: "/assets/images/teal_temple.jpg" },
    { prompt: "A starry indigo sky over a desert where glowing sand dunes shimmer like galaxies.", image: "/assets/images/indigo_desert.jpg" },
  ],
  FantasyWorlds: [
    { prompt: "A dragon playing chess with a wizard in a floating castle.", image: "/assets/images/dragon_chess.jpg" },
    { prompt: "A glowing portal in the middle of a snowy forest, revealing a vibrant tropical paradise.", image: "/assets/images/glowing_portal.jpg" },
    { prompt: "A kingdom built entirely on clouds, where people travel by flying boats.", image: "/assets/images/cloud_kingdom.jpg" },
    { prompt: "A mermaid gathering treasures in a bioluminescent underwater city.", image: "/assets/images/mermaid_treasures.jpg" },
  ],
  TimeTravel: [
    { prompt: "A Roman gladiator checking their smartwatch in the middle of the Colosseum.", image: "/assets/images/roman_gladiator_watch.jpg" },
    { prompt: "A caveman using a 3D printer to make tools in a prehistoric jungle.", image: "/assets/images/caveman_3d_printer.jpg" },
    { prompt: "A 1920s flapper dancing at a futuristic neon party.", image: "/assets/images/flapper_neon_party.jpg" },
    { prompt: "A time traveler stranded in a Victorian tea party with a malfunctioning robot.", image: "/assets/images/victorian_robot.jpg" },
  ],
  EverydayTwists: [
    { prompt: "A pizza delivery robot racing through a futuristic city during rush hour.", image: "/assets/images/pizza_robot.jpg" },
    { prompt: "A family of penguins shopping for groceries in a snowy supermarket.", image: "/assets/images/penguin_grocery.jpg" },
    { prompt: "A dog walking its human owner through a park filled with rainbow trees.", image: "/assets/images/dog_walking_human.jpg" },
    { prompt: "A street vendor selling flying carpets at a bustling bazaar.", image: "/assets/images/flying_carpets.jpg" },
  ],
  FuturisticSciFi: [
    { prompt: "A robot orchestra performing on a spaceship overlooking Earth.", image: "/assets/images/robot_orchestra.jpg" },
    { prompt: "A neon-lit diner floating in space, serving alien customers.", image: "/assets/images/space_diner.jpg" },
    { prompt: "A cyborg gardener planting glowing flowers in a zero-gravity greenhouse.", image: "/assets/images/cyborg_gardener.jpg" },
    { prompt: "An alien taxi driver navigating through a chaotic intergalactic traffic jam.", image: "/assets/images/alien_taxi.jpg" },
  ],
  Surrealism: [
    { prompt: "A giant clock melting over a bustling cityscape.", image: "/assets/images/melting_clock.jpg" },
    { prompt: "A staircase spiraling into the clouds, each step glowing with different colors.", image: "/assets/images/spiral_staircase.jpg" },
    { prompt: "A giraffe peeking out of a skyscraper window in the middle of a thunderstorm.", image: "/assets/images/giraffe_window.jpg" },
    { prompt: "A field of oversized flowers, each with a miniature galaxy inside its petals.", image: "/assets/images/galaxy_flowers.jpg" },
  ],
  MythsAndLegends: [
    { prompt: "Medusa running a trendy hair salon in a bustling marketplace.", image: "/assets/images/medusa_hair_salon.jpg" },
    { prompt: "Thor delivering a pizza using his hammer as transportation.", image: "/assets/images/thor_pizza.jpg" },
    { prompt: "A centaur winning a gold medal at the Olympics for high-speed running.", image: "/assets/images/centaur_olympics.jpg" },
    { prompt: "A phoenix delivering mail between cities by igniting the letters.", image: "/assets/images/phoenix_mail.jpg" },
  ],
};
